//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShumbiDiscover.Notes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShumbiDiscover.Notes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you close without saving, changes will be discarded..
        /// </summary>
        internal static string CHANGESWILLBEDISCARDED {
            get {
                return ResourceManager.GetString("CHANGESWILLBEDISCARDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqua.
        /// </summary>
        internal static string COLORAQUA {
            get {
                return ResourceManager.GetString("COLORAQUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string COLORBLACK {
            get {
                return ResourceManager.GetString("COLORBLACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string COLORBLUE {
            get {
                return ResourceManager.GetString("COLORBLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Gray.
        /// </summary>
        internal static string COLORBLUEGRAY {
            get {
                return ResourceManager.GetString("COLORBLUEGRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bright Green.
        /// </summary>
        internal static string COLORBRIGHTGREEN {
            get {
                return ResourceManager.GetString("COLORBRIGHTGREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        internal static string COLORBROWN {
            get {
                return ResourceManager.GetString("COLORBROWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Blue.
        /// </summary>
        internal static string COLORDARKBLUE {
            get {
                return ResourceManager.GetString("COLORDARKBLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Green.
        /// </summary>
        internal static string COLORDARKGREEN {
            get {
                return ResourceManager.GetString("COLORDARKGREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Red.
        /// </summary>
        internal static string COLORDARKRED {
            get {
                return ResourceManager.GetString("COLORDARKRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Teal.
        /// </summary>
        internal static string COLORDARKTEAL {
            get {
                return ResourceManager.GetString("COLORDARKTEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Yellow.
        /// </summary>
        internal static string COLORDARKYELLOW {
            get {
                return ResourceManager.GetString("COLORDARKYELLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string COLORGOLD {
            get {
                return ResourceManager.GetString("COLORGOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray 25%.
        /// </summary>
        internal static string COLORGRAY25 {
            get {
                return ResourceManager.GetString("COLORGRAY25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray 40%.
        /// </summary>
        internal static string COLORGRAY40 {
            get {
                return ResourceManager.GetString("COLORGRAY40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray 50%.
        /// </summary>
        internal static string COLORGRAY50 {
            get {
                return ResourceManager.GetString("COLORGRAY50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray 80%.
        /// </summary>
        internal static string COLORGRAY80 {
            get {
                return ResourceManager.GetString("COLORGRAY80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string COLORGREEN {
            get {
                return ResourceManager.GetString("COLORGREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indigo.
        /// </summary>
        internal static string COLORINDIGO {
            get {
                return ResourceManager.GetString("COLORINDIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lavender.
        /// </summary>
        internal static string COLORLAVENDER {
            get {
                return ResourceManager.GetString("COLORLAVENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Blue.
        /// </summary>
        internal static string COLORLIGHTBLUE {
            get {
                return ResourceManager.GetString("COLORLIGHTBLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Green.
        /// </summary>
        internal static string COLORLIGHTGREEN {
            get {
                return ResourceManager.GetString("COLORLIGHTGREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Orange.
        /// </summary>
        internal static string COLORLIGHTORANGE {
            get {
                return ResourceManager.GetString("COLORLIGHTORANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Turquoise.
        /// </summary>
        internal static string COLORLIGHTTURQUOISE {
            get {
                return ResourceManager.GetString("COLORLIGHTTURQUOISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Yellow.
        /// </summary>
        internal static string COLORLIGHTYELLOW {
            get {
                return ResourceManager.GetString("COLORLIGHTYELLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lime.
        /// </summary>
        internal static string COLORLIME {
            get {
                return ResourceManager.GetString("COLORLIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olive Green.
        /// </summary>
        internal static string COLOROLIVEGREEN {
            get {
                return ResourceManager.GetString("COLOROLIVEGREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string COLORORANGE {
            get {
                return ResourceManager.GetString("COLORORANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pale Blue.
        /// </summary>
        internal static string COLORPALEBLUE {
            get {
                return ResourceManager.GetString("COLORPALEBLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        internal static string COLORPINK {
            get {
                return ResourceManager.GetString("COLORPINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plum.
        /// </summary>
        internal static string COLORPLUM {
            get {
                return ResourceManager.GetString("COLORPLUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string COLORRED {
            get {
                return ResourceManager.GetString("COLORRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rose.
        /// </summary>
        internal static string COLORROSE {
            get {
                return ResourceManager.GetString("COLORROSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Green.
        /// </summary>
        internal static string COLORSEAGREEN {
            get {
                return ResourceManager.GetString("COLORSEAGREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky Blue.
        /// </summary>
        internal static string COLORSKYBLUE {
            get {
                return ResourceManager.GetString("COLORSKYBLUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan.
        /// </summary>
        internal static string COLORTAN {
            get {
                return ResourceManager.GetString("COLORTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teal.
        /// </summary>
        internal static string COLORTEAL {
            get {
                return ResourceManager.GetString("COLORTEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquoise.
        /// </summary>
        internal static string COLORTURQUOISE {
            get {
                return ResourceManager.GetString("COLORTURQUOISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        internal static string COLORVIOLET {
            get {
                return ResourceManager.GetString("COLORVIOLET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string COLORWHITE {
            get {
                return ResourceManager.GetString("COLORWHITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string COLORYELLOW {
            get {
                return ResourceManager.GetString("COLORYELLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue anyway?.
        /// </summary>
        internal static string CONTINUEANYWAY {
            get {
                return ResourceManager.GetString("CONTINUEANYWAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ballpoint Pen.
        /// </summary>
        internal static string INKBALLPOINT {
            get {
                return ResourceManager.GetString("INKBALLPOINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Ink.
        /// </summary>
        internal static string INKDELETE {
            get {
                return ResourceManager.GetString("INKDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All Ink.
        /// </summary>
        internal static string INKDELETEALL {
            get {
                return ResourceManager.GetString("INKDELETEALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felt Tip Pen.
        /// </summary>
        internal static string INKFELTTIP {
            get {
                return ResourceManager.GetString("INKFELTTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighter.
        /// </summary>
        internal static string INKHIGHLIGHTER {
            get {
                return ResourceManager.GetString("INKHIGHLIGHTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen Color.
        /// </summary>
        internal static string PENCOLOUR {
            get {
                return ResourceManager.GetString("PENCOLOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen Size.
        /// </summary>
        internal static string PENSIZE {
            get {
                return ResourceManager.GetString("PENSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As %1.
        /// </summary>
        internal static string SAVEAS {
            get {
                return ResourceManager.GetString("SAVEAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To %1.
        /// </summary>
        internal static string SENDTO {
            get {
                return ResourceManager.GetString("SENDTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string ZOOM {
            get {
                return ResourceManager.GetString("ZOOM", resourceCulture);
            }
        }
    }
}
