//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShumbiDiscover.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShumbiDiscover.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string ACCOUNT {
            get {
                return ResourceManager.GetString("ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string ACCOUNTS {
            get {
                return ResourceManager.GetString("ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Configuration.
        /// </summary>
        public static string CONFIGURATIONDELETE {
            get {
                return ResourceManager.GetString("CONFIGURATIONDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string CONFIGURE {
            get {
                return ResourceManager.GetString("CONFIGURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Address.
        /// </summary>
        public static string DOCUMENTCOMPLETEOPENURL {
            get {
                return ResourceManager.GetString("DOCUMENTCOMPLETEOPENURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upload has completed successfully. Copy and paste the address from the text box below, alternatively click the open button to view the page in your web browser..
        /// </summary>
        public static string DOCUMENTCOMPLETETITLE {
            get {
                return ResourceManager.GetString("DOCUMENTCOMPLETETITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string DOCUMENTCOMPLETEURL {
            get {
                return ResourceManager.GetString("DOCUMENTCOMPLETEURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string DOCUMENTISPUBLIC {
            get {
                return ResourceManager.GetString("DOCUMENTISPUBLIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string DOCUMENTKEYWORDS {
            get {
                return ResourceManager.GetString("DOCUMENTKEYWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter keywords, separated by commas..
        /// </summary>
        public static string DOCUMENTKEYWORDSINFO {
            get {
                return ResourceManager.GetString("DOCUMENTKEYWORDSINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string DOCUMENTTITLE {
            get {
                return ResourceManager.GetString("DOCUMENTTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string DOCUMENTVIEWERADDRESS {
            get {
                return ResourceManager.GetString("DOCUMENTVIEWERADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carousel.
        /// </summary>
        public static string DOCUMENTVIEWERCAROUSEL {
            get {
                return ResourceManager.GetString("DOCUMENTVIEWERCAROUSEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DOCUMENTVIEWERDESCRIPTION {
            get {
                return ResourceManager.GetString("DOCUMENTVIEWERDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string DOCUMENTVIEWERLIST {
            get {
                return ResourceManager.GetString("DOCUMENTVIEWERLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string DOCUMENTVIEWERRANK {
            get {
                return ResourceManager.GetString("DOCUMENTVIEWERRANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engines.
        /// </summary>
        public static string DOCUMENTVIEWERSEARCHENGINES {
            get {
                return ResourceManager.GetString("DOCUMENTVIEWERSEARCHENGINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles.
        /// </summary>
        public static string DOCUMENTVIEWERTILES {
            get {
                return ResourceManager.GetString("DOCUMENTVIEWERTILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string DOCUMENTVIEWERTITLE {
            get {
                return ResourceManager.GetString("DOCUMENTVIEWERTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string EMAILADDRESS {
            get {
                return ResourceManager.GetString("EMAILADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FAVOURITENAME {
            get {
                return ResourceManager.GetString("FAVOURITENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string FAVOURITESDELETE {
            get {
                return ResourceManager.GetString("FAVOURITESDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string FAVOURITESNEWFOLDER {
            get {
                return ResourceManager.GetString("FAVOURITESNEWFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string FAVOURITESOPEN {
            get {
                return ResourceManager.GetString("FAVOURITESOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string FAVOURITESRENAME {
            get {
                return ResourceManager.GetString("FAVOURITESRENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HISTORY {
            get {
                return ResourceManager.GetString("HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string HISTORYCLEAR {
            get {
                return ResourceManager.GetString("HISTORYCLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string HISTORYDATE {
            get {
                return ResourceManager.GetString("HISTORYDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string HISTORYDELETE {
            get {
                return ResourceManager.GetString("HISTORYDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string HISTORYOPEN {
            get {
                return ResourceManager.GetString("HISTORYOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string HISTORYSEARCH {
            get {
                return ResourceManager.GetString("HISTORYSEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engines.
        /// </summary>
        public static string HISTORYSEARCHENGINES {
            get {
                return ResourceManager.GetString("HISTORYSEARCHENGINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Used.
        /// </summary>
        public static string HISTORYSPACEUSED {
            get {
                return ResourceManager.GetString("HISTORYSPACEUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items To Keep.
        /// </summary>
        public static string HISTORYTOKEEP {
            get {
                return ResourceManager.GetString("HISTORYTOKEEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Days.
        /// </summary>
        public static string LICENSEDAYSREMAINING {
            get {
                return ResourceManager.GetString("LICENSEDAYSREMAINING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string LICENSEEXPIRYDATE {
            get {
                return ResourceManager.GetString("LICENSEEXPIRYDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Information.
        /// </summary>
        public static string LICENSEINFORMATION {
            get {
                return ResourceManager.GetString("LICENSEINFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase License.
        /// </summary>
        public static string LICENSEPURCHASE {
            get {
                return ResourceManager.GetString("LICENSEPURCHASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Type.
        /// </summary>
        public static string LICENSETYPE {
            get {
                return ResourceManager.GetString("LICENSETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password was incorrect..
        /// </summary>
        public static string LOGINFAILED {
            get {
                return ResourceManager.GetString("LOGINFAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication has successfully completed..
        /// </summary>
        public static string LOGINSUCCESS {
            get {
                return ResourceManager.GetString("LOGINSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string PASSWORDCHANGE {
            get {
                return ResourceManager.GetString("PASSWORDCHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password change did not succeed..
        /// </summary>
        public static string PASSWORDCHANGEFAIL {
            get {
                return ResourceManager.GetString("PASSWORDCHANGEFAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password was successfully changed..
        /// </summary>
        public static string PASSWORDCHANGESUCCESS {
            get {
                return ResourceManager.GetString("PASSWORDCHANGESUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string PASSWORDCURRENT {
            get {
                return ResourceManager.GetString("PASSWORDCURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string PASSWORDNEW {
            get {
                return ResourceManager.GetString("PASSWORDNEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PROPERTIES {
            get {
                return ResourceManager.GetString("PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string PROXY {
            get {
                return ResourceManager.GetString("PROXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string PROXYADDRESS {
            get {
                return ResourceManager.GetString("PROXYADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Proxy.
        /// </summary>
        public static string PROXYMANUAL {
            get {
                return ResourceManager.GetString("PROXYMANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Proxy.
        /// </summary>
        public static string PROXYNONE {
            get {
                return ResourceManager.GetString("PROXYNONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string PROXYPORT {
            get {
                return ResourceManager.GetString("PROXYPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Proxy.
        /// </summary>
        public static string PROXYSYSTEM {
            get {
                return ResourceManager.GetString("PROXYSYSTEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string PROXYSYSTEMDEFAULT {
            get {
                return ResourceManager.GetString("PROXYSYSTEMDEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same as Internet Explorer.
        /// </summary>
        public static string PROXYSYSTEMINTERNETEXPLORER {
            get {
                return ResourceManager.GetString("PROXYSYSTEMINTERNETEXPLORER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the history?.
        /// </summary>
        public static string QUESTIONCLEARHISTORY {
            get {
                return ResourceManager.GetString("QUESTIONCLEARHISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the favorite?.
        /// </summary>
        public static string QUESTIONDELETEFAVOURITE {
            get {
                return ResourceManager.GetString("QUESTIONDELETEFAVOURITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the folder and all of its contents?.
        /// </summary>
        public static string QUESTIONDELETEFAVOURITEFOLDER {
            get {
                return ResourceManager.GetString("QUESTIONDELETEFAVOURITEFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the history entry?.
        /// </summary>
        public static string QUESTIONDELETEHISTORY {
            get {
                return ResourceManager.GetString("QUESTIONDELETEHISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string SEARCHGROUPDOCUMENTS {
            get {
                return ResourceManager.GetString("SEARCHGROUPDOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string SEARCHGROUPPICTURES {
            get {
                return ResourceManager.GetString("SEARCHGROUPPICTURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Web.
        /// </summary>
        public static string SEARCHGROUPSOCIAL {
            get {
                return ResourceManager.GetString("SEARCHGROUPSOCIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string SEARCHGROUPVIDEOS {
            get {
                return ResourceManager.GetString("SEARCHGROUPVIDEOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Pages.
        /// </summary>
        public static string SEARCHGROUPWEB {
            get {
                return ResourceManager.GetString("SEARCHGROUPWEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS {
            get {
                return ResourceManager.GetString("SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SIGNUP {
            get {
                return ResourceManager.GetString("SIGNUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Cache.
        /// </summary>
        public static string THUMBNAILEMPTY {
            get {
                return ResourceManager.GetString("THUMBNAILEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to empty the thumbnail cache?.
        /// </summary>
        public static string THUMBNAILEMPTYQUESTION {
            get {
                return ResourceManager.GetString("THUMBNAILEMPTYQUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Location.
        /// </summary>
        public static string THUMBNAILLOCATION {
            get {
                return ResourceManager.GetString("THUMBNAILLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Cache.
        /// </summary>
        public static string THUMBNAILLOCATIONOPEN {
            get {
                return ResourceManager.GetString("THUMBNAILLOCATIONOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail Cache.
        /// </summary>
        public static string THUMBNAILS {
            get {
                return ResourceManager.GetString("THUMBNAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Size.
        /// </summary>
        public static string THUMBNAILSIZE {
            get {
                return ResourceManager.GetString("THUMBNAILSIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Used.
        /// </summary>
        public static string THUMBNAILSPACEUSED {
            get {
                return ResourceManager.GetString("THUMBNAILSPACEUSED", resourceCulture);
            }
        }
    }
}
