//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShumbiDiscover.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShumbiDiscover.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string ACTIONINFORMATION {
            get {
                return ResourceManager.GetString("ACTIONINFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        internal static string ALLFILES {
            get {
                return ResourceManager.GetString("ALLFILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotation Information.
        /// </summary>
        internal static string ANNOTATIONNFORMATION {
            get {
                return ResourceManager.GetString("ANNOTATIONNFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Complete.
        /// </summary>
        internal static string ANNOTATIONSENDCOMPLETE {
            get {
                return ResourceManager.GetString("ANNOTATIONSENDCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending annotation to %1.
        /// </summary>
        internal static string ANNOTATIONSENDINGTO {
            get {
                return ResourceManager.GetString("ANNOTATIONSENDINGTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve search result for annotation..
        /// </summary>
        internal static string ANNOTATIONUNABLETORETRIEVESEARCHRESULT {
            get {
                return ResourceManager.GetString("ANNOTATIONUNABLETORETRIEVESEARCHRESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem when trying to save the annotation..
        /// </summary>
        internal static string ANNOTATIONUNABLETOSAVE {
            get {
                return ResourceManager.GetString("ANNOTATIONUNABLETOSAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending annotation to %1 failed..
        /// </summary>
        internal static string ANNOTATIONUNABLETOSEND {
            get {
                return ResourceManager.GetString("ANNOTATIONUNABLETOSEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Cluster.
        /// </summary>
        internal static string CLUSTERCLOSE {
            get {
                return ResourceManager.GetString("CLUSTERCLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Cluster.
        /// </summary>
        internal static string CLUSTEREXPLORE {
            get {
                return ResourceManager.GetString("CLUSTEREXPLORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster Information.
        /// </summary>
        internal static string CLUSTERINFORMATION {
            get {
                return ResourceManager.GetString("CLUSTERINFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clustering.
        /// </summary>
        internal static string CLUSTERING {
            get {
                return ResourceManager.GetString("CLUSTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no selected clusters..
        /// </summary>
        internal static string CLUSTERSNONESELECTED {
            get {
                return ResourceManager.GetString("CLUSTERSNONESELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string CONFIGURATION {
            get {
                return ResourceManager.GetString("CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration has successfully been deleted..
        /// </summary>
        internal static string CONFIGURATIONDELETED {
            get {
                return ResourceManager.GetString("CONFIGURATIONDELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating.
        /// </summary>
        internal static string CREATING {
            get {
                return ResourceManager.GetString("CREATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string FAVOURITES {
            get {
                return ResourceManager.GetString("FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string FILES {
            get {
                return ResourceManager.GetString("FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HISTORY {
            get {
                return ResourceManager.GetString("HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing.
        /// </summary>
        internal static string INITIALISING {
            get {
                return ResourceManager.GetString("INITIALISING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough space available to save the data, do you agree to increasing the quota?.
        /// </summary>
        internal static string ISOLATEDSTORAGEINCREASE {
            get {
                return ResourceManager.GetString("ISOLATEDSTORAGEINCREASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual.
        /// </summary>
        internal static string LICENSEANNUAL {
            get {
                return ResourceManager.GetString("LICENSEANNUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation version.
        /// </summary>
        internal static string LICENSEEVALUATION {
            get {
                return ResourceManager.GetString("LICENSEEVALUATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web page can not be opened. Your browser&apos;s popup blocker could be preventing it from opening..
        /// </summary>
        internal static string POPUPBLOCKER {
            get {
                return ResourceManager.GetString("POPUPBLOCKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string PROGRESS {
            get {
                return ResourceManager.GetString("PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your login credentials for %1.
        /// </summary>
        internal static string PROVIDERLOGIN {
            get {
                return ResourceManager.GetString("PROVIDERLOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not have an account for %1 then click the button below to take you to the web site. Once you have signed up you can return here and enter your information..
        /// </summary>
        internal static string PROVIDERSIGNUP {
            get {
                return ResourceManager.GetString("PROVIDERSIGNUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering.
        /// </summary>
        internal static string RENDERING {
            get {
                return ResourceManager.GetString("RENDERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Engines.
        /// </summary>
        internal static string SEARCHENGINES {
            get {
                return ResourceManager.GetString("SEARCHENGINES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching.
        /// </summary>
        internal static string SEARCHING {
            get {
                return ResourceManager.GetString("SEARCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotate Search Result.
        /// </summary>
        internal static string SEARCHRESULTANNOTATE {
            get {
                return ResourceManager.GetString("SEARCHRESULTANNOTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Search Result.
        /// </summary>
        internal static string SEARCHRESULTOPEN {
            get {
                return ResourceManager.GetString("SEARCHRESULTOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string SEARCHRESULTTYPEDOCUMENT {
            get {
                return ResourceManager.GetString("SEARCHRESULTTYPEDOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string SEARCHRESULTTYPEPICTURE {
            get {
                return ResourceManager.GetString("SEARCHRESULTTYPEPICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types of Search Results.
        /// </summary>
        internal static string SEARCHRESULTTYPES {
            get {
                return ResourceManager.GetString("SEARCHRESULTTYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Web.
        /// </summary>
        internal static string SEARCHRESULTTYPESOCIAL {
            get {
                return ResourceManager.GetString("SEARCHRESULTTYPESOCIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        internal static string SEARCHRESULTTYPEVIDEO {
            get {
                return ResourceManager.GetString("SEARCHRESULTTYPEVIDEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Pages.
        /// </summary>
        internal static string SEARCHRESULTTYPEWEB {
            get {
                return ResourceManager.GetString("SEARCHRESULTTYPEWEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizations.
        /// </summary>
        internal static string VISUALISATIONS {
            get {
                return ResourceManager.GetString("VISUALISATIONS", resourceCulture);
            }
        }
    }
}
