//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShumbiDiscover.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShumbiDiscover.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string ACTIONINFORMATION {
            get {
                return ResourceManager.GetString("ACTIONINFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annotate Item.
        /// </summary>
        internal static string ANNOTATEITEM {
            get {
                return ResourceManager.GetString("ANNOTATEITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Cluster.
        /// </summary>
        internal static string CLOSECLUSTER {
            get {
                return ResourceManager.GetString("CLOSECLUSTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster Information.
        /// </summary>
        internal static string CLUSTERINFORMATION {
            get {
                return ResourceManager.GetString("CLUSTERINFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clustering....
        /// </summary>
        internal static string CLUSTERING {
            get {
                return ResourceManager.GetString("CLUSTERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string CONFIGURATION {
            get {
                return ResourceManager.GetString("CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration has successfully been deleted..
        /// </summary>
        internal static string CONFIGURATIONDELETED {
            get {
                return ResourceManager.GetString("CONFIGURATIONDELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Image....
        /// </summary>
        internal static string CREATINGIMAGE {
            get {
                return ResourceManager.GetString("CREATINGIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating PDF....
        /// </summary>
        internal static string CREATINGPDF {
            get {
                return ResourceManager.GetString("CREATINGPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating XPS....
        /// </summary>
        internal static string CREATINGXPS {
            get {
                return ResourceManager.GetString("CREATINGXPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Information.
        /// </summary>
        internal static string DOCUMENTINFORMATION {
            get {
                return ResourceManager.GetString("DOCUMENTINFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Types.
        /// </summary>
        internal static string DOCUMENTTYPES {
            get {
                return ResourceManager.GetString("DOCUMENTTYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Upload Complete.
        /// </summary>
        internal static string DOCUMENTUPLOADCOMPLETE {
            get {
                return ResourceManager.GetString("DOCUMENTUPLOADCOMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string FAVOURITES {
            get {
                return ResourceManager.GetString("FAVOURITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string HISTORY {
            get {
                return ResourceManager.GetString("HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string INITIALISING {
            get {
                return ResourceManager.GetString("INITIALISING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough space available to save the data, is it OK to increase the quota used ?.
        /// </summary>
        internal static string ISOLATEDSTORAGEINCREASE {
            get {
                return ResourceManager.GetString("ISOLATEDSTORAGEINCREASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual.
        /// </summary>
        internal static string LICENSEANNUAL {
            get {
                return ResourceManager.GetString("LICENSEANNUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        internal static string LICENSETRIAL {
            get {
                return ResourceManager.GetString("LICENSETRIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LOADING {
            get {
                return ResourceManager.GetString("LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no clusters selected..
        /// </summary>
        internal static string NOCLUSTERSSELECTED {
            get {
                return ResourceManager.GetString("NOCLUSTERSSELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Cluster.
        /// </summary>
        internal static string OPENCLUSTER {
            get {
                return ResourceManager.GetString("OPENCLUSTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Item.
        /// </summary>
        internal static string OPENITEM {
            get {
                return ResourceManager.GetString("OPENITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the page, is your browsers popup blocker stopping the page from opening ?.
        /// </summary>
        internal static string POPUPBLOCKER {
            get {
                return ResourceManager.GetString("POPUPBLOCKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string PROGRESS {
            get {
                return ResourceManager.GetString("PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendering content....
        /// </summary>
        internal static string RENDERINGCONTENT {
            get {
                return ResourceManager.GetString("RENDERINGCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving Data....
        /// </summary>
        internal static string RETRIEVINGDATA {
            get {
                return ResourceManager.GetString("RETRIEVINGDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string SEARCHING {
            get {
                return ResourceManager.GetString("SEARCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Providers.
        /// </summary>
        internal static string SEARCHPROVIDERS {
            get {
                return ResourceManager.GetString("SEARCHPROVIDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string SEARCHRESULTTYPEDOCUMENT {
            get {
                return ResourceManager.GetString("SEARCHRESULTTYPEDOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        internal static string SEARCHRESULTTYPEMOVIE {
            get {
                return ResourceManager.GetString("SEARCHRESULTTYPEMOVIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string SEARCHRESULTTYPEPICTURE {
            get {
                return ResourceManager.GetString("SEARCHRESULTTYPEPICTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        internal static string SEARCHRESULTTYPESOCIAL {
            get {
                return ResourceManager.GetString("SEARCHRESULTTYPESOCIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        internal static string SEARCHRESULTTYPEWEB {
            get {
                return ResourceManager.GetString("SEARCHRESULTTYPEWEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Clusters.
        /// </summary>
        internal static string SUBCLUSTERS {
            get {
                return ResourceManager.GetString("SUBCLUSTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to render web page..
        /// </summary>
        internal static string UNABLETORENDERWEBPAGE {
            get {
                return ResourceManager.GetString("UNABLETORENDERWEBPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to save the annotation..
        /// </summary>
        internal static string UNABLETOSAVEANNOTATION {
            get {
                return ResourceManager.GetString("UNABLETOSAVEANNOTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to upload document to.
        /// </summary>
        internal static string UNABLETOUPLOADDOCUMENT {
            get {
                return ResourceManager.GetString("UNABLETOUPLOADDOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading document to.
        /// </summary>
        internal static string UPLOADINGDOCUMENTO {
            get {
                return ResourceManager.GetString("UPLOADINGDOCUMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizations.
        /// </summary>
        internal static string VISUALISATIONS {
            get {
                return ResourceManager.GetString("VISUALISATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizing....
        /// </summary>
        internal static string VISUALISING {
            get {
                return ResourceManager.GetString("VISUALISING", resourceCulture);
            }
        }
    }
}
